### ISSUE TITLE
Tracking Issue for improvements for built-in declarative defaults generator

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/gengo#193]
Originally PR linked here: https://github.com/kubernetes/gengo/pull/192

Future Improvements:
- Avoid `reflect.ValueOf` and precompute the zero values instead. https://github.com/kubernetes/gengo/pull/192#discussion_r520952124
- Unmarshal once for structs/arrays/maps and use shallow/deep copy instead of unmarshalling every time https://github.com/kubernetes/gengo/pull/192#discussion_r520952702
- Create a defaulting function to call instead of generating the code every time a defaulter is needed https://github.com/kubernetes/gengo/pull/192#discussion_r521637246
- Decompose `writeDefaulter` into separate functions https://github.com/kubernetes/gengo/pull/192#discussion_r522391330
- Remove PruneDefaults from openapi test https://github.com/kubernetes/kubernetes/blob/dee67230af5ee72f616c46856bf5c700d0c9b6b9/pkg/generated/openapi/openapi_test.go#L34

We should target these for the beginning of 1.21

**Comment by apelisse** [comment]
We need to address the comment on [round-tripping the spec through json](https://github.com/kubernetes/kubernetes/blob/master/pkg/generated/openapi/openapi_test.go#L34-L35). This is caused because there is some confusion in the code about what generates integers and what generates floats. Ideally, the type would be explicit everywhere so that they wouldn't be converted by accident.

**Comment by apelisse** [comment]
We need a test to show that we can assign floats properly: https://github.com/kubernetes/gengo/blob/master/examples/defaulter-gen/_output_tests/marker/type.go#L23

**Comment by Jefftree** [comment]
/close

I think we covered all the tasks that we wanted to do.
