### ISSUE TITLE
are `--input-dirs` directories or packages

### ISSUE THREAD

**Issue by MHBauer** [kubernetes/gengo#39]
Using lister-gen from https://github.com/kubernetes/kubernetes/tree/master/cmd/libs/go2idl/lister-gen

`--input-dirs` only accepts packages and not directories. Is lister-gen using the input-dirs argument incorrectly, or is the argument supposed to represent directories and not packages?

**Comment by thockin** [comment]
I think it is not well defined, but the ones I look at all use pkg names

**Comment by MHBauer** [comment]
I have the same experience, which is what prompted the question. Can we consider changing that flag then? Or deprecating + hiding it and adding a new flag with the old flag as an alias? I wouldn't want to break everyone.

**Comment by thockin** [comment]
yeah, deprecating and hiding is a must.  I'd be fine to change it to
--input-pkgs or perhaps even just assume that non-flag args == input dirs.

instead of `cmd --input-pkgs=foo,bar,bat` do `cmd foo bar bat`.  Slightly
larger change, but I think better.  @lavalamp might know a reason not to do
this...

**Comment by thockin** [comment]
Will be fixed in v2 (https://github.com/kubernetes/gengo/pull/259)
